#!/bin/bash
rm -fv /usr/share/polkit-1/actions/store.spark-app.spark-store.policy

# Update certain caches
update-icon-caches /usr/share/icons/hicolor || true
update-desktop-database /usr/share/applications || true
update-mime-database /usr/share/mime || true
